apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      # - image: dockersamples/examplevotingapp_result:before
      # - image: kodekloud/examplevotingapp_result:v1
      - image: halilintar8/example-voting-app_result:latest
      # - image: localhost:5000/example-voting-app_result:latest
        name: result
        ports:
        - containerPort: 80
          name: result
