apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      # - image: dockersamples/examplevotingapp_vote:before
      # - image: kodekloud/examplevotingapp_vote:v1
      - image: halilintar8/example-voting-app_vote:latest
      # - image: localhost:5000/example-voting-app_vote:latest
        # imagePullPolicy: Always
        name: vote
        ports:
        - containerPort: 80
          name: vote
