apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      # - image: dockersamples/examplevotingapp_worker
      # - image: kodekloud/examplevotingapp_worker:v1
      - image: halilintar8/example-voting-app_worker:latest
      # - image: localhost:5000/example-voting-app_worker:latest
        name: worker
